# Generated by Django 4.0.1 on 2024-01-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(default='Some default description'),
        ),
        migrations.AddField(
            model_name='room',
            name='participants',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
