# Generated by Django 4.0.1 on 2024-01-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_description_room_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(default='Lets Chat'),
        ),
    ]
